type Address {
    id: ID!
    streetName: String!
    number: Int!
    city: String!
    state: String!
    country: String!
}

type User {
    id: ID!
    name: String!
    email: String!
    posts: [Post!]!
    comments: [Comment!]!
}

type Post {
    id: ID!
    title: String!
    body: String!
    published: Boolean!
    author: User!
    comments: [Comment!]!
}

type Comment {
    id: ID!
    text: String!
    author: User!
    post: Post!
} 

enum MutationType {
    CREATED
    DELETED
    UPDATED
}

type PostSubscriptionPayload {
    mutation: MutationType!
    node: Post
}


type CommentPreviousValues {
    id: ID!
    text: String!
}

type CommentSubscriptionPayload {
    mutation: MutationType!
    node: Comment
    # updatedFields: [String!]
    # previousValues: CommentPreviousValues
}
