
type User {
    id: ID!
    name: String!
    email: String!
    posts: [Post!]!
    comments: [Comment!]!
}

type Query {
    users(query: String): [User!]!
}

type Mutation {
    createUser(data: CreateUserInput!): User!
    updateUser(id: ID!, data: UpdateUserInput!): User!
    deleteUser(id: String!): User!
}

type Subscription {
    newUser: UserSubscriptionPayload!
}

type UserSubscriptionPayload {
    mutation: MutationType!
    node: User
}

input CreateUserInput {
    name: String!
    email: String!
}

input UpdateUserInput {
    name: String
    email: String
}